pull_request_rules:
  - name: automatic merge Dependabot updates on CI success
    conditions:
      - author=dependabot[bot]
      - base=master
      - status-success=continuous-integration/appveyor/branch
    actions:
      merge:
        method: rebase
        rebase_fallback: merge
        strict: smart
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
